//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Dob { get; set; }
        public bool Gender { get; set; }
        public string ParentName { get; set; }
        public int ParentPhoneNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> DietId { get; set; }
        public Nullable<int> TakingCareId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Diet Diet { get; set; }
        public virtual TakingCare TakingCare { get; set; }
    }
}
