//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Trip
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int TripId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
