//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kindergarten_DBEntities : DbContext
    {
        public Kindergarten_DBEntities()
            : base("name=Kindergarten_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Class_Trip> Class_Trip { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<DietDetail> DietDetails { get; set; }
        public virtual DbSet<TakingCare> TakingCares { get; set; }
        public virtual DbSet<TakingCareDetail> TakingCareDetails { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Teacher_Class> Teacher_Class { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripDetail> TripDetails { get; set; }
        public virtual DbSet<TaskEvent> TaskEvents { get; set; }
    }
}
