//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDetail
    {
        public int Id { get; set; }
        public string Destination { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public string Activity { get; set; }
        public string Food { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public int TripId { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
